[package]
name = "btm"
version = "0.8.1"
edition = "2021"
keywords = ["vcs", "snapshot", "zfs", "btrfs"]
license = "MIT"
authors = ["ccmlm","fanhui.x@gmail.com"]
description = "Blockchain Time Machine"
homepage = "https://github.com/ccmlm/btm"
repository = "https://github.com/ccmlm/btm.git"

[dependencies]
ruc = { version = "2.0", features = ["rich"]}
clap = { version = "3.2.22", features = ["derive"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
nix = "0.25"

[[bin]]
name = "btm"
path = "src/bins/btm.rs"
