[package]
name = "btm"
version = "0.11.1"
edition = "2021"
keywords = ["vcs", "snapshot", "zfs", "btrfs"]
license = "MIT"
authors = ["fanhui.x@gmail.com"]
description = "Blockchain Time Machine"
homepage = "https://github.com/rust-util-collections/btm"
repository = "https://github.com/rust-util-collections/btm.git"

[dependencies]
ruc = { version = "3.0", features = ["cmd","uau"]}
clap = { version = "4.0.18", features = ["cargo","derive"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
nix = "0.25"

[[bin]]
name = "btm"
path = "src/bins/btm.rs"
